improving bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -2,20 +2,57 @@
 
 cd "${HOME}" || exit 1
 
+# i never know where yadm's config directory will be
+if [[ -d $HOME/.config/yadm/repo.git ]]; then
+    YADM_REPO=$HOME/.config/yadm/repo.git
+elif [[ -d $HOME/.local/share/yadm/repo.git ]]; then
+    YADM_REPO=$HOME/.local/share/yadm/repo.git
+fi
+
+INSTALL_DEPENDENCIES=${INSTALL_DEPENDENCIES:-true}
+DEPENDENCIES=(
+    curl
+    vim
+    zsh
+    fzf
+    pass
+)
+
+echo "Validating packages and dependencies"
+for i in ${DEPENDENCIES[@]}; do
+    if ! command -v  &> /dev/null; then
+        if [[ $INSTALL_DEPENDENCIES == true ]]; then
+            if [[ ${OSTYPE} == linux-gnu ]]; then
+                sudo apt install -y $i
+            fi
+        else
+            echo "$i: not in PATH or not installed, failing"
+            exit 1
+        fi
+    fi
+done
+
 echo "Init submodules"
 yadm submodule update --recursive --init
 
-echo "Install oh-my-zsh"
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+if ! [[ -d $HOME/.oh-my-zsh ]]; then
+    echo "Install oh-my-zsh"
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+    yadm checkout .zshrc --quiet
+fi
 
-echo "Installing vim plug"
-curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
-    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+if ! [[ -f $HOME/.vim/autoload/plug.vim ]]; then
+    echo "Installing vim plug"
+    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
+        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+fi
+
+echo "Installing vim plugins"
 vim +PlugInstall +qall
 
 # prevent certain files from being present
 yadm gitconfig core.sparseCheckout true
-cat << EOF > "$HOME/.local/share/yadm/repo.git/info/sparse-checkout"
+cat << EOF > "${YADM_REPO}/info/sparse-checkout"
 # generated by $0
 /*
 !README.md
